administracion/urls.py
"""Configuración URLs de administracion"""

# Django
from django.urls import path

# App usuarios
from administracion import views as administracion_views
from administracion.views import alumnos as alumnos_views
from administracion.views import dojos as dojos_views
from administracion.views import cursillos as cursos_views
from administracion.views import actividades as actividades_views
from administracion.views import tablon as tablon_views
from administracion.views import varios as varios_views
from administracion.views import directiva as directiva_views

# Asegúrate de tener un namespace
app_name = 'administracion'

urlpatterns = [
    # Alumnos
    path("alumnos/", alumnos_views.AlumnosView.as_view(), name="alumnos"),
    path("alumnos/<int:pk>/", alumnos_views.AlumnoDetailView.as_view(), name="alumno_detalle"),
    path("alumnos/grado/<int:grado>/", alumnos_views.AlumnosView.as_view(), name="alumnos_grado"),
    # Dojos
    path("dojos/", dojos_views.DojosView.as_view(), name="dojos"),
    path("dojos/<int:pk>/", dojos_views.DojoDetailView.as_view(), name="dojo_detalle"),
    # Cursillos
    path("cursillos/", cursos_views.CursillosView.as_view(), name="cursillos"),
    path("cursillos/<int:pk>/", cursos_views.CursilloDetailView.as_view(), name="cursillo_detalle"),
    path("cursillos/<int:pk>/examinados", cursos_views.CursilloExaminaListView.as_view(), name="cursillo_examinados"),
    path("cursillos/<int:pk>/estadisticas", cursos_views.CursilloEstadisticasView.as_view(), name="cursillo_estadisticas"),
    path("cursillos/<int:pk>/circular", cursos_views.descargar_circular, name="descargar_circular"),
    path("cursillos/<int:pk>/inscripcion", cursos_views.CursilloInscripcionInstructorView.as_view(), name="cursillo_inscripcion_instructor"),
    path("curso/nuevo/", administracion_views.CursoNuevoView.as_view(), name="curso_nuevo"),
    # Peticiones
    path("peticiones/", administracion_views.PeticionView.as_view(), name="peticiones"),
    path("peticiones/anular/<int:pk>/", administracion_views.PeticionAnularView.as_view(), name="peticiones_anular"),
    # Directiva
    #path("directiva/", directiva_views.DirectivaView.as_view(), name="directiva"),
    # Actividades
    path("actividades/", actividades_views.ActividadesView.as_view(), name="actividades"),
    path("actividades/editar/<int:pk>/", actividades_views.ActividadEditarView.as_view(), name="editar_actividad"),
    path("actividades/eliminar/<int:pk>/", actividades_views.ActividadEliminarView.as_view(), name="eliminar_actividad"),
    # Tablon
    path("tablon/", tablon_views.TablonView.as_view(), name="tablon"),
    path("tablon/editar/<int:pk>/", tablon_views.TablonEditarView.as_view(), name="editar_tablon"),
    path("tablon/eliminar/<int:pk>/", tablon_views.TablonEliminarView.as_view(), name="eliminar_tablon"),
    # Varios
    path("correo/", varios_views.enviar_correo_instructores, name="correo"),
    path("error/<int:error_code>/", varios_views.ErrorView.as_view(), name="errores"),
]

ogkke/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from administracion import views as administracion_views

urlpatterns = [
    path("", administracion_views.home, name='home'),
    path("usuarios/", include("usuarios.urls")),
    path("administracion/", include("administracion.urls")),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administracion/views/actividades.py
"""
Vistas relacionadas con la gestión de actividades
"""

# Python
import datetime

# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, UpdateView, DeleteView
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.template.loader import render_to_string

# App administracion
from administracion.models import Actividad

# Formularios
from administracion.forms import ActividadNuevaForm, ActividadEditForm

# Utilidades
from administracion.utils import is_ajax

class ActividadesView(LoginRequiredMixin, TemplateView):
    """
    Gestión de actividades
    """

    template_name = "administracion/actividades.html"

    def get_context_data(self, **kwargs):
        """
        Obtenemos todas las actividades
        """

        context = super().get_context_data(**kwargs)

        # Obtenemos la fecha actual
        hoy = datetime.date.today()
        context["actividades"] = Actividad.objects.filter(fecha__gte=hoy).order_by('fecha')
        context['form'] = ActividadNuevaForm()

        return context

    def post(self, request, *args, **kwargs):
        """
        Procesa el formulario de nueva actividad
        """

        # Obtenemos los datos del formulario
        form = ActividadNuevaForm(request.POST)
        if form.is_valid():
            try:
                titulo = form.cleaned_data['titulo']
                descripcion = form.cleaned_data['descripcion']
                fecha = form.cleaned_data['fecha']
                lugar = form.cleaned_data['lugar']
                ciudad = form.cleaned_data['ciudad']
                provincia = form.cleaned_data['provincia']
                pais = form.cleaned_data['pais']

                # Creamos la nueva actividad
                Actividad.objects.create(
                    titulo = titulo,
                    descripcion = descripcion,
                    fecha = fecha,
                    lugar = lugar,
                    ciudad = ciudad,
                    provincia = provincia,
                    pais = pais,
                )
                messages.success(self.request, "¡Actividad creada exitosamente!")
            except Exception as e:
                messages.error(self.request, f"Ocurrió un error al crear la actividad: {e}")
        else:
            messages.error(self.request, f'Ocurrió un error al crear la actividad: {form.errors}')

        return redirect('administracion:actividades')


class ActividadEditarView(LoginRequiredMixin, UpdateView):
    """
    Editar una actividad
    """

    model = Actividad
    form_class = ActividadEditForm
    template_name = 'administracion/actividades.html'
    success_url = reverse_lazy("administracion:actividades")

    # Sobrescribimos el método GET
    def get(self, request, *args, **kwargs):
        # Si la petición es AJAX, no devolvemos la página completa.
        if is_ajax(request):
            # Obtenemos el objeto que se está editando (UpdateView lo hace por nosotros)
            self.object = self.get_object()
            form = self.get_form()
            context = {'form': form, 'actividad': self.object}
            
            # Renderizamos solo el formulario parcial y lo devolvemos en un JSON
            html_form = render_to_string(
                'administracion/modales/modal_actividad_edit_form.html',
                context,
                request=request
            )
            return JsonResponse({'html_form': html_form})
        else:
            # Si no es AJAX, dejamos que UpdateView haga su trabajo normal
            return super().get(request, *args, **kwargs)
        
    # Sobrescribimos el método que se llama cuando el formulario es válido
    def form_valid(self, form):
        # Guardamos el objeto
        print(f'DEBUG: Formulario válido, guardando objeto')
        self.object = form.save()
        
        if is_ajax(self.request):
            # Si es AJAX, devolvemos un JSON indicando que todo fue bien
            return JsonResponse({'success': True, 'message': 'Actividad actualizada correctamente.'})
        else:
            # Si no, hacemos la redirección normal
            return super().form_valid(form)
        
    # Sobrescribimos el método que se llama cuando el formulario tiene errores
    def form_invalid(self, form):
        print(f'DEBUG: Formulario inválido: {form.errors}')
        if is_ajax(self.request):
            # Si es AJAX, renderizamos de nuevo el formulario con los errores
            # y lo devolvemos en un JSON para que el cliente lo muestre.
            context = {'form': form, 'actividad': self.get_object()}
            html_form = render_to_string(
                'administracion/modales/modal_actividad_edit_form.html',
                context,
                request=self.request
            )
            return JsonResponse({'success': False, 'html_form': html_form}, status=400)
        else:
            # Si no, dejamos que se renderice la página con los errores del formulario
            return super().form_invalid(form)
    


class ActividadEliminarView(LoginRequiredMixin, DeleteView):
    """
    Vista para eliminar una actividad
    """

    model = Actividad
    success_url = reverse_lazy('administracion:actividades')

administracion/views/alumnos.py
"""
Vistas relacionadas con la gestión de los alumnos
"""

# Python
import datetime
import json

# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from django.db.models import Count

# App administracion
from administracion.models import Alumno, Examen

class AlumnosView(LoginRequiredMixin, ListView):
    """
    Vista de alumnos por grado
    """
    model = Alumno
    template_name = 'administracion/alumnos.html'
    context_object_name = 'alumnos'
    # paginate_by = 10


    def get_queryset(self):
        """
        Define la consulta para obtener los alumnos por grado.
        Filtra por el grado obtenido en los parametros de la url
        Ordena los resultados
        """

        # Obtiene el valor de 'grado' de los argumentos de la URL (kwargs)
        # Si no se pasa 'grado' en la URL, usa 1 como valor predeterminado.
        grado = self.kwargs.get('grado', 1)
        queryset = super().get_queryset().filter(grado=grado).order_by('dojo', 'apellidos')
        # Alternativamente, podrías escribirlo sin llamar a super() aquí:
        #queryset = Alumno.objects.filter(grado=grado).order_by('dojo', 'apellidos')

        return queryset


    def get_context_data(self, **kwargs):
        """
        Obtenemos los datos de los cintos negros para hacer el grafico de barras

        Returns:
            El número de cintos negros por grado
        """
        context = super().get_context_data(**kwargs)
        grado = self.kwargs.get('grado', 1)
        context['grado'] = grado

        # Obtenemos los datos para hacer el gráfico de barras
        data = Alumno.objects.values('grado').annotate(total=Count('id')).order_by('grado')

        labels = [item['grado'] for item in data]
        values = [item['total'] for item in data]
        data_json = json.dumps({
            'labels': labels,
            'values': values,
            'titulo': 'Número de alumnos por grado',})
        context['data_json'] = data_json

        # Obtenemos la cantidad de cintos negros en la consulta
        if self.context_object_name in context:
            context['cantidad'] = context[self.context_object_name].count()
        else:
            context['cantidad'] = self.get_queryset().count()

        context['grados_posibles'] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

        return context


class AlumnoDetailView(LoginRequiredMixin, DetailView):
    """
    Muestra los detalles de un alumno específico.
    Los exámenes que ha realizado y el tiempo que ha estado en cada grado
    """
    model = Alumno
    template_name = 'administracion/detalle_alumno.html' # Crea esta plantilla
    context_object_name = 'alumno' # Nombre del objeto en la plantilla detalle

    def get_context_data(self, **kwargs):
        """
        Calculamos los eventos en los que se ha examinado y los años en cada grado
        """
        # Creamos las variables locales para los calculos
        anios = list()
        examen = list()
        hoy = datetime.date.today()
        # Llama a la implementación de la base para obtener el contexto inicial
        context = super(AlumnoDetailView, self).get_context_data(**kwargs)
        # Obtiene el objeto alumno actual
        alumno = self.get_object()

        # Obtenemos la lista de examenes de ese alumno
        examenes = Examen.objects.filter(alumno=alumno.id)

        for idx, exam in enumerate(examenes):
            examen.append(str(exam.grado) + " DAN")
            print(exam.evento.evento)
            print(exam.evento.fecha)
            # Verificamos si el indica actual es el último de la lista
            if idx == len(examenes) - 1:
                anios.append(hoy.year - exam.evento.fecha.year)
            else:
                anios.append(examenes[idx + 1].evento.fecha.year - exam.evento.fecha.year)

        # Preparamos el contexto para la plantilla
        context['examen'] = examen
        context['examenes'] = examenes
        context['hoy'] = hoy
        context['anios'] = anios
        context['total_anios'] = sum(anios)
        # Combinamos dos listas para poder sber los años de cada grado en el timeline de la plantilla
        # Este enfoque permite recorrer dos listas de forma sincronizada
        anios_danes = list(zip(examenes, anios))
        context['examenes_anios'] = anios_danes

        # Calculamos la edad del alumno
        if alumno.fecha_nacimiento is None:
            edad_a = 0
            edad_b = 0
        else:
            edad = hoy - alumno.fecha_nacimiento
            edad = divmod(edad.days, 365)
            edad_a = edad[0]
            edad_b = edad[1]
        context['edad'] = edad_a

        # Preparamos el gráfico
        data_json = json.dumps({
            'labels': examen,
            'values': anios,
            'titulo': 'Años en cada grado',
        })
        context['data_json'] = data_json

        return context

administracion/views/directiva.py
"""
    Vistas relacionadas con la gestión del equipo directivo
"""

# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView

# App administracion
from administracion.models import MiembroDirectiva

class DirectivaView(LoginRequiredMixin, ListView):
    """Vista del equipo directivo"""
    model = MiembroDirectiva
    template_name = 'administracion/organigrama.html'
    # Definimos el queryset base: solo activos y optimizamos consultas con select_related
    queryset = MiembroDirectiva.objects.filter().select_related('cargo', 'alumno', 'usuario')

    def get_context_data(self, **kwargs):
        # Llamamos a la implementación base para obtener el contexto estándar
        context = super().get_context_data(**kwargs)
        qs = self.get_queryset()

        # Separamos la lógica jerárquica dentro del contexto
        # 1. Buscamos al cargo con menor orden (asumimos que es el Presidente)
        context['presidente'] = qs.order_by('cargo__orden_jerarquico').first()
        
        # 2. Miembros de la ejecutiva (excluyendo al presidente)
        context['ejecutiva'] = qs.filter().exclude(id=context['presidente'].id if context['presidente'] else None)
        
        return context
    

administracion/views/home.py
""" Vistas de la app administracion """

# Python
import datetime
import json

# Django

from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from django.db.models import Count

# App administracion
from administracion.models import Alumno, Cursillo, Dojo, Actividad

@login_required
def home(request):
    """
    Home de la aplicación

    Devolvemos datos globales
    - El total de cinturones negros, dojos, cursillos tanto nacionales como internacionales
    - La cantidad de alumnos por danes
    """

    hoy = datetime.date.today()
    actividades = Actividad.objects.filter(fecha__gte=hoy).order_by('fecha')
    cn = Alumno.objects.all().count()
    cursos = Cursillo.objects.all().count()
    nacional = Cursillo.objects.filter(pais='España').count()
    internacional = Cursillo.objects.filter(internacional=True).count()
    extranjero = Cursillo.objects.exclude(pais='España').count()
    dojos = Dojo.objects.all().count()
    data = Alumno.objects.values('grado').annotate(total=Count('id')).order_by('grado')
    labels = [item['grado'] for item in data]
    values = [item['total'] for item in data]
    data_json = json.dumps({
        'labels': labels,
        'values': values,
        'titulo': 'Número de alumnos por grado',
    })

    return render(request, 'administracion/home.html', {
        'cn': cn,
        'cursos': cursos,
        'nacional': nacional,
        'internacional': internacional,
        'extranjero': extranjero,
        'dojos': dojos,
        'hoy': hoy,
        'actividades': actividades,
        'data_json': data_json,
    })

templates/administracion/cursillo_estadisticas.html
{% extends "base.html" %}
{% load static %}

{% block container %}
    
    {% include "administracion/header.html" %}

        <!-- Breadcrumb -->
        <!-- Colocado dentro del container, debajo de la nav y antes del H1 -->
        <nav class="mt-5" aria-label="breadcrumb" style="--bs-breadcrumb-divider: '>';"> <!-- Opcional: Cambia el separador -->
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Inicio</a></li>
                <li class="breadcrumb-item"><a href="{% url 'administracion:cursillos' %}">Cursillo</a></li>
                <li class="breadcrumb-item active text-warning" aria-current="page">Detalle Cursillo</li>
            </ol>
        </nav>
        <!-- Fin Breadcrumb -->

        <!-- Título Principal -->
        <h1 class="text-center mt-5 mb-5 color-texto">Detalle Cursillo</h1>

        <div class="row row-cols-1 mt-5">
            <div class="card mt-3">
                <div class="card-header">
                  {% if cursillo.internacional %}Internacional{% else %}Nacional{% endif %}
                </div>
                <div class="card-body">
                    <h5 class="card-title color-texto">{{ cursillo.evento }}</h5>
                    <p class="card-text"><i class="bi bi-calendar3"></i> {{ cursillo.fecha }}</p>
                    {% if cursillo.descripcion != None %}
                        <p class="card-text">{{ cursillo.descripcion }}</p>
                    {% endif %}
                    <p class="card-text">{{ cursillo.lugar }}. {{ cursillo.ciudad }}, {{ cursillo.pais }}</p>
                    {% if cursillo.fecha > hoy %}
                    <div class="d-flex justify-content-end">
                        <button type="button" class="btn btn-outline-warning" data-bs-toggle="modal" data-bs-target="#modalInscripcion">
                            <i class="bi bi-list-ul"></i> Inscripción</button>
                        {% if cursillo.circular != '' %}
                            <a href="{% url 'administracion:cursillos' %}" class="btn btn-outline-warning ms-4"><i class="bi bi-arrow-up-right-circle"></i> Circular</a>
                        {% endif %}
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>

        <!-- Pestañas -->
        <section class="album py-5">
            <div class="container">
                
                <div class="row row-cols-1">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a href="{% url 'administracion:cursillo_detalle' pk=cursillo.id %}" class="nav-link">Asistentes</a>
                        </li>
                        {% if cursillo.examenes %}
                            <li class="nav-item">
                                <a href="{% url 'administracion:cursillo_examinados' pk=cursillo.id %}" class="nav-link">Exámen</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a href="#" class="nav-link active">Estadísticas</a>
                        </li>
                    </ul>
                </div>
        
                <div class="row row-cols-1 mt-5">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Dojo</th>
                                <th>Total de Asistentes</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in estadisticas_asistentes_por_dojo %}
                            <tr>
                                <td>{{ item.dojo__nombre }}</td>
                                <td>{{ item.total_asistentes }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>   
                    <div class="container">
                        <div class="d-none d-md-block d-flex justify-content-center mt-5">
                            <canvas id="graficoAsistentesPorDojo"></canvas>
                        </div>
                    </div>
                </div>    
            </div>
        </section>
        <!-- Fin listado de alumnos asistentes -->

        {% endblock container %}

{% block script_js %}

<script>
    //new DataTable('#tbalumno');
    $('#tbalumno').DataTable({
        "pageLength": 25,
        "responsive": true,
        "language": {
            search: "Buscar en la tabla ",
            info: "Mostrando _START_ a _END_ de _TOTAL_ registros",
            infoEmpty: "Mostrando 0 a 0 de 0 registros",
            infoFiltered: "(filtrado de _MAX_ registros totales)",
            lengthMenu: "Mostrar _MENU_ registros",
            zeroRecords: "No se encontraron registros",
            paginate: {
                first: "Primera",
                last: "Última",
                next: "Siguiente",
                previous: "Anterior"
            },
        }
    });

    // Gráfica asistentes por dojo
    const data = JSON.parse('{{ asistentes_por_dojo|safe }}'); // Obtener los datos como objeto JavaScript

    const ctx = document.getElementById('graficoAsistentesPorDojo');
    const config = {
        type: 'bar',
        data: {
            datasets: [{
                label: '',
                data: data.values,
                backgroundColor: [
                    'rgba(54, 162, 235, 0.2)',
                ],
                borderColor: [
                    'rgba(54, 162, 235, 1)',
                ],
                borderWidth: 2,
                borderRadius: 10,
                datalabels: { // Configuración de chartjs-plugin-datalabels para ESTE dataset
                    display: false // Oculta las etiquetas de datos solo para este dataset
                },
            }],
            labels: data.labels,
        },
        options: {
            indexAxis: 'y',
            responsive: true,
            plugins: {
                legend: {
                    display: false // Esto oculta la leyenda completamente
                },
            },
            scales: { // Configuración del eje Y sin porcentajes
                x: {
                    beginAtZero: true,
                    ticks: {
                        stepSize: 1
                    }
                }
            }          
        },
    };

    const myChart = new Chart(ctx, config); 
    
</script>


{% endblock script_js %}

templates/administracion/detalle_cursillo.html
{% extends "base.html" %}
{% load static %}

{% block container %}
    
    {% include "administracion/header.html" %}

        <!-- Breadcrumb -->
        <!-- Colocado dentro del container, debajo de la nav y antes del H1 -->
        <nav class="mt-5" aria-label="breadcrumb" style="--bs-breadcrumb-divider: '>';"> <!-- Opcional: Cambia el separador -->
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Inicio</a></li>
                <li class="breadcrumb-item"><a href="{% url 'administracion:cursillos' %}">Cursillo</a></li>
                <li class="breadcrumb-item active text-warning" aria-current="page">Detalle Cursillo</li>
            </ol>
        </nav>
        <!-- Fin Breadcrumb -->

        <!-- Título Principal -->
        <h1 class="text-center mt-5 mb-5 color-texto">Detalle Cursillo</h1>

        {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
        {% endif %}

        <div class="row row-cols-1 mt-5">
            <div class="card mt-3">
                <div class="card-header">
                  {% if cursillo.internacional %}Internacional{% else %}Nacional{% endif %}
                </div>
                <div class="card-body">
                    <h5 class="card-title color-texto">{{ cursillo.evento }}</h5>
                    <p class="card-text"><i class="bi bi-calendar3"></i> {{ cursillo.fecha }}</p>
                    {% if cursillo.descripcion != None %}
                        <p class="card-text">{{ cursillo.descripcion }}</p>
                    {% endif %}
                    <p class="card-text">{{ cursillo.lugar }}. {{ cursillo.ciudad }}, {{ cursillo.pais }}</p>
                    {% if cursillo.fecha > hoy %}
                    <div class="d-flex justify-content-end">
                        {% if usuario_es_instructor or user.is_staff or user.is_superuser %}
                            <a href="{% url 'administracion:cursillo_inscripcion_instructor' pk=cursillo.id %}" class="btn btn-outline-warning ms-4"><i class="bi bi-list-ul"></i> Inscripción</a>
                        {% else %}
                            {% if alumno_cursillo_inscrito %}
                                <button type="button" class="btn btn-outline-warning" data-bs-toggle="modal" data-bs-target="#modalInscripcionAlumno">
                                <i class="bi bi-list-ul"></i> Eliminar</button>
                            {% else %}
                                <button type="button" class="btn btn-outline-warning" data-bs-toggle="modal" data-bs-target="#modalInscripcionAlumno">
                                <i class="bi bi-list-ul"></i> Inscripción</button>
                            {% endif %}
                        {% endif %}
                        {% if cursillo.circular != '' %}
                            <a href="{% url 'administracion:descargar_circular' pk=cursillo.id %}" class="btn btn-outline-warning ms-4"><i class="bi bi-download"></i> Circular</a>
                        {% endif %}
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>

        
        <!-- Listado de alumnos asistentes -->
        <section class="album py-5">
            <div class="container">
                
                <div class="row row-cols-1">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a href="#" class="nav-link active">Asistentes</a>
                        </li>
                        {% if cursillo.examenes %}
                            <li class="nav-item">
                                <a href="{% url 'administracion:cursillo_examinados' pk=cursillo.id %}" class="nav-link">Exámen</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a href="{% url 'administracion:cursillo_estadisticas' pk=cursillo.id %}" class="nav-link">Estadísticas</a>
                        </li>
                    </ul>
                </div>
        
                <div class="row row-cols-1 mt-5">
        
                    {% if asistentes %}
                        <div class="col mt-5">
                            <div class="row">
                                <table id="tbalumno" class="table table-striped display">
                                    <thead>
                                    <tr>
                                        <th>Nombre</th>
                                        <th>Gimnasio</th>
                                        <th>Grado</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for alm in asistentes %}
                                        <tr>
                                            <td><a class="link-underline link-underline-opacity-0 link-offset-2 link-underline-opacity-100-hover"
                                                    href="{% url 'administracion:alumno_detalle' pk=alm.id %}">{{ alm.apellidos }}, {{ alm.nombre }}
                                                </a></td>
                                            <td>{{ alm.dojo }}</td>
                                            <td>{{ alm.grado }}</td>
                                        </tr>		
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    {% endif %}
        
                </div>    
            </div>
        </section>
        <!-- Fin listado de alumnos asistentes -->

        <!-- Modal Inscripción Alumno -->
        <div class="modal fade" id="modalInscripcionAlumno" tabindex="-1" aria-labelledby="modalInscripcionAlumnoLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5 color-texto" id="modalInscripcionAlumnoLabel">Inscripcion alumno</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <h3>Te vas a inscribir en el curso</h3>
                        <p>{{ cursillo.descripcion }}</p>
                        <p>De fecha {{ cursillo.fecha|date:"d-m-Y" }}</p>
                    </div>
                    <div class="modal-footer">
                        <a href="{% url 'administracion:cursillo_inscripcion_instructor' pk=cursillo.id %}" class="btn btn-outline-warning ms-4"><i class="bi bi-list-ul"></i> Inscripción</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Fin Modals -->

        {% endblock container %}

{% block script_js %}

<script>
    //new DataTable('#tbalumno');
    $('#tbalumno').DataTable({
        "pageLength": 25,
        "responsive": true,
        "language": {
            search: "Buscar en la tabla ",
            info: "Mostrando _START_ a _END_ de _TOTAL_ registros",
            infoEmpty: "Mostrando 0 a 0 de 0 registros",
            infoFiltered: "(filtrado de _MAX_ registros totales)",
            lengthMenu: "Mostrar _MENU_ registros",
            zeroRecords: "No se encontraron registros",
            paginate: {
                first: "Primera",
                last: "Última",
                next: "Siguiente",
                previous: "Anterior"
            },
        }
    });
</script>


{% endblock script_js %}